# Generated by Django 4.2.3 on 2024-04-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_bankaccount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="routing_number",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="pin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
